# Generated by Django 5.2.7 on 2025-11-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
