# Generated by Django 5.2.7 on 2025-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_enrollment_completed_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentprogress',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
